<?php
/**
 * ACF functions.
 */
class HTR_ACF {
	/**
	 * Add Wordpress' actions and filters.
	 */
	function __construct() {
		add_action('acf/init', [$this, 'options_page']);
		add_action('acf/init', [$this, 'acf_fields']);
	}

	/**
	 * Add ACF options page.
	 */
	public function options_page() {
		acf_add_options_page();
	}

	/**
	 * ACF Content
	 */
	public function acf_fields() {
		if (function_exists('acf_add_local_field_group')):
			acf_add_local_field_group(array(
				'key' => 'group_61b25a3567733',
				'title' => 'Options',
				'fields' => array(
					array(
						'key' => 'field_61b25ac3700a8',
						'label' => 'Réseaux Sociaux',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_61b25ae6700a9',
						'label' => 'Réseaux',
						'name' => 'social-networks',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'row',
						'button_label' => 'Ajouter un réseau social',
						'sub_fields' => array(
							array(
								'key' => 'field_61b25b52700ab',
								'label' => 'Sélectionnez le réseau',
								'name' => 'site',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'youtube' => 'YouTube',
									'instagram' => 'Instagram',
									'twitter' => 'Twitter',
									'facebook' => 'Facebook',
									'twitch' => 'Twitch',
									'autre' => 'Autre',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'array',
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_61b25ae6700a9',
							),
							array(
								'key' => 'field_61b25b15700aa',
								'label' => 'Lien',
								'name' => 'url',
								'aria-label' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'parent_repeater' => 'field_61b25ae6700a9',
							),
						),
						'rows_per_page' => 20,
					),
					array(
						'key' => 'field_622941936f03b',
						'label' => 'Shop',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_622942276f03c',
						'label' => 'Nombre de produits par page',
						'name' => 'products-per-page',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'Change le nombre de produits affichés par page sur la vue principale de la boutique.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 16,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 4,
						'max' => '',
						'step' => 1,
					),
					array(
						'key' => 'field_6296695e6581f',
						'label' => 'Supplément carburant',
						'name' => 'shipping-taxes',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_629669e165820',
								'label' => 'Supplément service Standard',
								'name' => 'shipping-tax-std',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '0,00%',
								'prepend' => '',
								'append' => '%',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_62966a6565821',
								'label' => 'Supplément service Express',
								'name' => 'shipping-tax-express',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '0,00%',
								'prepend' => '',
								'append' => '%',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
					),
					array(
						'key' => 'field_6295a9b53bc73',
						'label' => 'Description globale produit',
						'name' => 'product-description',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => 'Le texte sera affiché sous chaque produit',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_62a1fcc07db4c',
						'label' => 'Annonce globale',
						'name' => 'notification',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => 'Cette annonce apparaîtra en haut des pages de la boutique',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_62902a49c297e',
						'label' => 'Pied de page',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_62902a6ec297f',
						'label' => 'Bordures asymétriques',
						'name' => 'footer-borders',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => 'Affiche des bordures asymétriques en haut et en bas du bloc du pied de page',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_62abd153b4615',
						'label' => 'Autres',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_62abd16cb4616',
						'label' => 'Pages non-indexables',
						'name' => 'no-index',
						'aria-label' => '',
						'type' => 'relationship',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'page',
						),
						'taxonomy' => '',
						'filters' => array(
							0 => 'search',
							1 => 'post_type',
						),
						'elements' => '',
						'min' => '',
						'max' => '',
						'return_format' => 'id',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'options_page',
							'operator' => '==',
							'value' => 'acf-options',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));

			acf_add_local_field_group(array(
				'key' => 'group_619560d1d446f',
				'title' => 'Page — Accueil',
				'fields' => array(
					array(
						'key' => 'field_6195613164fd8',
						'label' => 'Hero',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_61956219d6ef7',
						'label' => 'Bloc Hero',
						'name' => 'block-hero',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_619561787cb25',
								'label' => 'Actif',
								'name' => 'is-active',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => 'Active / Désactive l’affichage du bloc.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 1,
								'ui' => 1,
								'ui_on_text' => 'Activé',
								'ui_off_text' => 'Désactivé',
							),
							array(
								'key' => 'field_61956246d6ef8',
								'label' => 'Contenu',
								'name' => 'content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => 'Contenu affiché dans le bloc',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_619561787cb25',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_619562a5d6ef9',
								'label' => 'Image de fond',
								'name' => 'background',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => 'Si le champ est laissé vide, un fond uni (noir) sera affiché.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_619561787cb25',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'large',
								'library' => 'all',
								'min_width' => 1920,
								'min_height' => 1080,
								'min_size' => '',
								'max_width' => 2560,
								'max_height' => '',
								'max_size' => 2,
								'mime_types' => 'jpg,jpeg,webp',
							),
							array(
								'key' => 'field_629026e21dd09',
								'label' => 'Bordure asymétrique',
								'name' => 'borders',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => 'Ajoute ou non une bordure asymétrique en bas du bloc.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 1,
								'ui_on_text' => 'Actif',
								'ui_off_text' => 'Inactif',
							),
						),
					),
					array(
						'key' => 'field_61d3cab7ff10a',
						'label' => 'Showcase',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_61d3cad1ff10b',
						'label' => 'Bloc Showcase',
						'name' => 'block-showcase',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_61d3cb00ff10e',
								'label' => 'Actif',
								'name' => 'is-active',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => 'Active / Désactive l’affichage du bloc.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 1,
								'ui' => 1,
								'ui_on_text' => 'Activé',
								'ui_off_text' => 'Désactivé',
							),
							array(
								'key' => 'field_61d3cae6ff10c',
								'label' => 'Titre',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_619561787cb25',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_61d3caf2ff10d',
								'label' => 'Contenu',
								'name' => 'content',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_619561787cb25',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_61d3cbfdff10f',
								'label' => 'Lien',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_619561787cb25',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_61d3cc13ff110',
										'label' => 'URL',
										'name' => 'url',
										'aria-label' => '',
										'type' => 'page_link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => '',
										'taxonomy' => '',
										'allow_null' => 0,
										'allow_archives' => 1,
										'multiple' => 0,
									),
									array(
										'key' => 'field_61d3cc42ff111',
										'label' => 'Label',
										'name' => 'label',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
							),
						),
					),
					array(
						'key' => 'field_61d3bf2bd1d56',
						'label' => 'Carte',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_61d3bf40d1d57',
						'label' => 'Bloc Carte',
						'name' => 'block-map',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_61d3bf64d1d58',
								'label' => 'Afficher la carte',
								'name' => 'is-active',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => 'Affiche ou non la carte sur la page d’accueil',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 1,
								'ui' => 1,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_61d3bfa8d1d59',
								'label' => 'API Token',
								'name' => 'token',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'Token à récupérer sur https://account.mapbox.com/',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_61d3bf64d1d58',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_61d3c089d1d5a',
								'label' => 'Style',
								'name' => 'style',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'URL de style à récupérer sur https://cloud.maptiler.com/',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_61d3bf64d1d58',
											'operator' => '==',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_629027fa4db17',
								'label' => 'Bordures asymétriques',
								'name' => 'borders',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => 'Ajoute ou non une bordure asymétrique en haut et en bas du bloc.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 1,
								'ui_on_text' => 'Actif',
								'ui_off_text' => 'Inactif',
							),
						),
					),
					array(
						'key' => 'field_61956a7f8b7e1',
						'label' => 'Derniers Produits',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_61956c9747d4d',
						'label' => 'Bloc Derniers Produits',
						'name' => 'block-latest-products',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6229bcd040437',
								'label' => 'Activer',
								'name' => 'is-active',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 1,
								'ui_on_text' => 'Actif',
								'ui_off_text' => 'Inactif',
							),
							array(
								'key' => 'field_629d66795ecae',
								'label' => 'Nombre de produits affichés',
								'name' => 'number',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 4,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 4,
								'max' => 10,
								'step' => 1,
							),
							array(
								'key' => 'field_629d66a95ecaf',
								'label' => 'Bordures asymétriques',
								'name' => 'borders',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => 'Ajoute ou non une bordure asymétrique en haut et en bas du bloc.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 1,
								'ui_on_text' => 'Actif',
								'ui_off_text' => 'Inactif',
							),
						),
					),
					array(
						'key' => 'field_629d66c85ecb0',
						'label' => 'Sélection de produits',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_629d66dd5ecb1',
						'label' => 'Bloc Sélection de produits',
						'name' => 'block-best-products',
						'aria-label' => '',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_629d66dd5ecb2',
								'label' => 'Activer',
								'name' => 'is-active',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 1,
								'ui_on_text' => 'Actif',
								'ui_off_text' => 'Inactif',
							),
							array(
								'key' => 'field_629d67015ecb5',
								'label' => 'Produits Sélectionnés',
								'name' => 'products',
								'aria-label' => '',
								'type' => 'relationship',
								'instructions' => 'Choisir les produits qui seront affichés sur la page (minimum 4, maximum 10)',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'post_type' => array(
									0 => 'product',
								),
								'taxonomy' => '',
								'filters' => array(
									0 => 'search',
								),
								'elements' => array(
									0 => 'featured_image',
								),
								'min' => 4,
								'max' => 12,
								'return_format' => 'id',
							),
							array(
								'key' => 'field_629d66dd5ecb4',
								'label' => 'Bordures asymétriques',
								'name' => 'borders',
								'aria-label' => '',
								'type' => 'true_false',
								'instructions' => 'Ajoute ou non une bordure asymétrique en haut et en bas du bloc.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 1,
								'ui_on_text' => 'Actif',
								'ui_off_text' => 'Inactif',
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'page_template',
							'operator' => '==',
							'value' => 'page-home.php',
						),
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'page',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'the_content',
					1 => 'excerpt',
					2 => 'discussion',
					3 => 'comments',
					4 => 'revisions',
					5 => 'slug',
					6 => 'author',
					7 => 'format',
					8 => 'page_attributes',
					9 => 'featured_image',
					10 => 'categories',
					11 => 'tags',
					12 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));

			acf_add_local_field_group(array(
				'key' => 'group_630acedc1f17b',
				'title' => 'Page — Nos films',
				'fields' => array(
					array(
						'key' => 'field_630acf0dac135',
						'label' => 'movies',
						'name' => 'movies',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => 'field_630acf89ac136',
						'min' => 0,
						'max' => 0,
						'layout' => 'block',
						'button_label' => 'Ajouter un film',
						'sub_fields' => array(
							array(
								'key' => 'field_630acf89ac136',
								'label' => 'Titre',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'parent_repeater' => 'field_630acf0dac135',
							),
							array(
								'key' => 'field_630acfb7ac137',
								'label' => 'Image mobile',
								'name' => 'picture-mobile',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => 'Affiche au format portrait pour mobile',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '10',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => 1,
								'mime_types' => 'jpg,jpeg,avif,png,webp',
								'parent_repeater' => 'field_630acf0dac135',
							),
							array(
								'key' => 'field_630ad00dac138',
								'label' => 'Image PC',
								'name' => 'picture-desktop',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => 'Affiche au format paysage pour PC',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '10',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => 1,
								'mime_types' => 'jpg,jpeg,avif,png,webp',
								'parent_repeater' => 'field_630acf0dac135',
							),
							array(
								'key' => 'field_630ad0cfac139',
								'label' => 'Description',
								'name' => 'description',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
								'parent_repeater' => 'field_630acf0dac135',
							),
							array(
								'key' => 'field_630ad0ddac13a',
								'label' => 'Lien',
								'name' => 'link',
								'aria-label' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'parent_repeater' => 'field_630acf0dac135',
							),
						),
						'rows_per_page' => 20,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'page',
						),
						array(
							'param' => 'page_template',
							'operator' => '==',
							'value' => 'page-movies.php',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'the_content',
					1 => 'excerpt',
					2 => 'discussion',
					3 => 'comments',
					4 => 'revisions',
					5 => 'slug',
					6 => 'author',
					7 => 'format',
					8 => 'page_attributes',
					9 => 'featured_image',
					10 => 'categories',
					11 => 'tags',
					12 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));

			acf_add_local_field_group(array(
				'key' => 'group_6292adca74b41',
				'title' => 'Page — Présentation',
				'fields' => array(
					array(
						'key' => 'field_6292ae011a295',
						'label' => 'Auteur',
						'name' => 'author',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'row',
						'button_label' => 'Ajouter une personne',
						'sub_fields' => array(
							array(
								'key' => 'field_6292ae2d1a296',
								'label' => 'Nom complet',
								'name' => 'name',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'parent_repeater' => 'field_6292ae011a295',
							),
							array(
								'key' => 'field_6292ae3f1a297',
								'label' => 'Photo',
								'name' => 'picture',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'shop_catalog',
								'library' => 'all',
								'min_width' => 400,
								'min_height' => 300,
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
								'parent_repeater' => 'field_6292ae011a295',
							),
							array(
								'key' => 'field_6292aeb81a298',
								'label' => 'Description',
								'name' => 'description',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'basic',
								'media_upload' => 1,
								'delay' => 0,
								'parent_repeater' => 'field_6292ae011a295',
							),
						),
						'rows_per_page' => 20,
					),
					array(
						'key' => 'field_6292ba65faf4d',
						'label' => 'Suite du contenu',
						'name' => 'content',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_6292bbc615638',
						'label' => 'Vidéo',
						'name' => 'video',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => 'Lien vers une vidéo YouTube (ou autre site de contenu vidéo). Si ce lien n’est pas renseigné, le bloc ne sera pas affiché.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'https://www.youtube.com/watch?v=lPazowgxz0o',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'page',
							'operator' => '==',
							'value' => '235',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));

			acf_add_local_field_group(array(
				'key' => 'group_6292dc2549a5e',
				'title' => 'Produits',
				'fields' => array(
					array(
						'key' => 'field_6295ab0b41b1e',
						'label' => 'Filtres',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_6295a19641050',
						'label' => 'Pays',
						'name' => 'country',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => 'Choisir le pays',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'fr' => 'France',
							'hk' => 'Hong Kong',
							'ua' => 'Ukraine',
							'br' => 'Brésil',
							'ae' => 'Dubaï',
							'gb' => 'Angleterre',
							'be' => 'Belgique',
							'bg' => 'Bulgarie',
							'gr' => 'Géorgie',
							'it' => 'Italie',
							'pl' => 'Pologne',
							'pt' => 'Portugal',
							'th' => 'Thaïlande',
							'us' => 'USA',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6295ac1641b21',
						'label' => 'Années',
						'name' => 'origin-year',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'Choisissez une année',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 2010,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 2010,
						'max' => '',
						'step' => 1,
					),
					array(
						'key' => 'field_6295ad204a370',
						'label' => 'Type',
						'name' => 'type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'under' => 'Souterrains',
							'outside' => 'Extérieurs',
							'upper' => 'Hauteurs',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6295abc341b20',
						'label' => 'Personnage',
						'name' => 'character',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'with' => 'Avec',
							'without' => 'Sans',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6295aace41b1d',
						'label' => 'Couleurs',
						'name' => 'colors',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'hot' => 'Couleurs chaudes',
							'cold' => 'Couleurs froides',
							'bw' => 'Noir & blanc',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6295aa8f41b1c',
						'label' => 'Orientation',
						'name' => 'orientation',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'landscape' => 'Paysage',
							'portrait' => 'Portrait',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'array',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'product',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'the_content',
					1 => 'excerpt',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));

		endif;
	}
}
new HTR_ACF();
